
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testview:
    name: Test View Class
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Compiler
      run: | 
         sudo apt-get update
         sudo apt-get install g++
    - name: Compile Test
      run: g++ test/test_view.cc -I ./ 
    - name: Run
      run: ./a.out

  testtensor:
    name: Test Tensor Class
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run: g++ test/test_tensor.cc -I ./ 
    - name: Run
      run: ./a.out

  elementvspytorch:
    name : Element Indexing VS PyTorch
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run: g++ test/test_tensor_indexing_with_pytorch_element.cc -I ./ 
    - name: Run
      run: ./a.out

  bulkvspytorch:
    name: Bulk Indexing VS PyTorch
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run:  g++ test/test_tensor_indexing_with_pytorch.cc -I ./ 
    - name: Run
      run:  ./a.out
