name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test_view:
    name: View Class
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Compiler
      run: | 
         sudo apt-get update
         sudo apt-get install g++
    - name: Compile Test
      run: g++ test/test_view.cc -I ./ 
    - name: Run
      run: ./a.out

  test_tensor_constructors:
    name: Tensor Constructors 
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run: g++ test/test_tensor_constructors.cc -I ./ 
    - name: Run
      run: ./a.out

  test_tensor_constructor_helpers:
    name: Tensor Constructor Helpers 
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run: g++ test/test_tensor_constructor_helpers.cc -I ./ 
    - name: Run
      run: ./a.out

  test_tensor_api:
    name: Tensor API 
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run: g++ test/test_tensor_api.cc -I ./ 
    - name: Run
      run: ./a.out

  test_tensor_api:
    name: Statistical randn() tests 
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run: g++ test/test_tensor_random_distributions.cc -I ./ 
    - name: Run
      run: ./a.out

  element_vs_pytorch:
    name : Element Indexing VS PyTorch
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run: g++ test/test_tensor_indexing_with_pytorch_element.cc -I ./ 
    - name: Run
      run: ./a.out

  bulkvspytorch:
    name: Bulk Indexing VS PyTorch
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Compile Test
      run:  g++ test/test_tensor_indexing_with_pytorch.cc -I ./ 
    - name: Run
      run:  ./a.out
