
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testview:
    name: Test View Class
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Compiler
       run: sudo apt-get install g++
    - name: Compile Test
       run: g++ test/test_view.cc -I /
    - name: Run
       run: test/a.out
